Fixed text in chknet() and added error code 1 in case of failure.

diff --git a/usr/bin/otto b/usr/bin/otto
--- a/usr/bin/otto
+++ b/usr/bin/otto
@@ -111,15 +111,14 @@ chknet(){
     printf "[ ${GREEN}OK$END ]\n"
   else
     printf "[ ${RED}FAILED$END ]\n"
-    printf "Apparently, this box ${RED}isn't connected$END to the World Wide Web.\a\n
-    If you don't have a internet connection, try to download the raw package (a ${YELLOW}$PKG_FORMT$END which contains the source-code/program files and a build/install file), save it in a diskette, CD, SDCard or USB and install it using ${YELLOW}otto dig -raw$END.\n
-    If you expected to have networking on this box, ${BLK_RED}do some checks$BLK_END. Check if the network daemon is running, if the drivers are enabled on the Kernel and if the physical devices are even working/turned on.\n"
+    printf "${RED}ERROR$END: Apparently, this box ${RED}isn't connected$END to the World Wide Web.\a\nIf you don't have a internet connection, try to download the raw package (a ${YELLOW}$PKG_FORMT$END which contains the source-code/program files and a build/install file), save it in a diskette/CD/SDCard/USB and install it using ${YELLOW}otto dig [raw|-r]$END.\nIf you expected to have networking on this box, ${BLK_RED}do some checks$BLK_END. Check if the network daemon is running, if the drivers are enabled on the Kernel and if the physical devices are even working/turned on.\n"
+    exit 1
   fi
 }
 
 chkparams(){
   if [ -z "$1" ]; then
-    printf "${RED}ERROR:$END Insufficient parameters.\n"
+    printf "${RED}ERROR$END: Insufficient parameters.\n"
     exit 127
   fi
 }
