Added more "UNIXisms" in program flags, made the script more portable.

diff --git a/usr/bin/otto b/usr/bin/otto
--- a/usr/bin/otto
+++ b/usr/bin/otto
@@ -104,14 +104,14 @@ fi
 chknet(){
     printf "Checking network connection"
     txtwait
-if printf "GET luiznet.tk HTTP/1.0\n\n" | netcat luiznet.tk 80 > /dev/null 2>&1
+if  printf "GET luiznet.tk HTTP/1.0\n\n" | timeout 12 netcat luiznet.tk 80 > /dev/null 2>&1
 then
     kill $WAITPID
     printf "[ ${GREEN}OK$END ]\n"
 else
     kill $WAITPID
     printf "[ ${RED}FAILED$END ]\n"
-    printf "Apparently, this box ${RED}isn't connected$END to the World Wide Web.\n
+    printf "Apparently, this box ${RED}isn't connected$END to the World Wide Web.\a\n
     If you don't have a internet connection, try to download the raw package (a ${YELLOW}$PKG_FORMT$END which contains the source-code/program files and a build/install file), save it in a diskette, CD, SDCard or USB and install it using ${YELLOW}otto dig -raw$END.\n
     If you expected to have networking on this box, ${BLK_RED}do some checks$BLK_END. Check if the network daemon is running, if the drivers are enabled on the Kernel and if the physical devices are even working/turned on.\n"
 }
@@ -153,9 +153,14 @@ autoclean(){
 }
 
 pkgdown(){
-    for torrent in "$@"; do
-	PKGNM=$(printf "$torrent\n" | cut -d "/" -f 2)
-	/usr/bin/otto-torrent -s -f "/usr/otto/db/$torrent.otlink" -d $SRCDIR
+    for TORRENT in "$@"; do
+	#TO BE IMPLEMENTED: Install packages from any directory
+	#DASHES=${TORRENT//[^\/]}
+	#PKGNM=$(printf "$TORRENT\n" | cut -d "/" -f ${#DASHES})
+	#or, a more portable alternative
+	#PKGNM=$(printf "$TORRENT\n" | cut -d "/" -f `printf "$TORRENT\n" | grep -o '/' | wc -l`)
+	PKGNM=`printf "$TORRENT\n" | cut -d "/" -f 2`
+	/usr/bin/otto-torrent -s -f "/usr/otto/db/$TORRENT.otlink" -d $SRCDIR
     done
 }
 
@@ -211,8 +216,8 @@ if [ -f "$OTTOETC/package.installed" ]; then
     printf '%s\n' "$lines installed packages."
     exit 0
 else
-    printf "${BLK_RED}ERROR:$BLK_END package list not found!.\n
-    exit 128+n
+    printf "${BLK_RED}ERROR:$BLK_END package list not found!.\a\n"
+    exit 140
 fi
 }
 
@@ -236,14 +241,14 @@ help(){
     printf "\
 ${GREEN}Otto $VER, ein paketmanager.$END
 
-> help    - Show this help message.
-> info    - List info about the software.
-> find    - Search for content in Otto's files.
-> dig     - Install package.
-> bury    - Remove package.
-> up2date - Update repository index and packages.
-> mkpkg   - Build a package (using source code or binaries). 
-> list    - List installed packages.
+> -help (-H)    - Show this help message.
+> -info (-I)    - List info about the software.
+> -find (-f)    - Search for content in Otto's files.
+> -dig  (-d)    - Install package.
+> -bury (-b)    - Remove package.
+> -up2date (-u) - Update repository index and packages.
+> -mkpkg (-mp)  - Build a package (using source code or binaries). 
+> -list  (-l)   - List installed packages.
 
 ✠ GOTT MIT UNS ✠
 "
@@ -260,15 +265,14 @@ find(){
 
 ############## CASE DO SCRIPT #################
 case $1 in
-	help*) help "$2" ;;
-	info*) info "$2" ;;
-        find*) find "$2" ;;
-	dig*) install "$2" ;;
-	bury*) remove "$2" ;;
-	up2date*) update "$2" ;;
-	mkpkg*) mkpkg "$2" ;;
-        list*) list "$2" ;;
-	*) help "$2" ;;
+	-help|help|-H*) help ;;
+	-info|info|-I*) info ;;
+        -find|find|-f*) find "$@" ;;
+	-dig|dig|-d*) install "$@" ;;
+	-bury|bury|-b*) remove "$@" ;;
+	-up2date|up2date|-u*) update "$@" ;;
+	-mkpkg|mkpkg|-mp*) mkpkg "$2" ;;
+        -list|list|-l*) list "$@" ;;
+	*) help ;;
 esac
 ############## FIM DO CASE ####################
-
