Fixed major errors, reestructred parts of the code.

diff --git a/usr/bin/otto b/usr/bin/otto
--- a/usr/bin/otto
+++ b/usr/bin/otto
@@ -30,18 +30,24 @@ export LC_ALL="${LANG}"
 ##############     END       ##############
 
 ############# Export alias ##########
-# This shall be commented when /bin/sh already has a native "chdir" command/system call, for example zsh.
-alias chdir='cd'
+alias chdir='cd' # This shall be commented when /bin/sh already has a native "chdir" command/system call.
 alias editor="/usr/bin/env ${EDITOR}"
+alias sourcelocalpkginfo=". "${PKGDIR}"/"${TORRENT}"/pkginfo"
 ##############     END       ##############
 
 ############## Global Variables/Subshells #
+# Shell to be used at "dropping Shell sessions"
+if [ -z "${DROP_SHELL}" ]; then
+  export SHELL='ksh'
+else
+  export SHELL="${DROP_SHELL}"
+fi
 # Package and category name pipeline
-export PKG="`/usr/bin/cut -d "/" -f 2 <<< "$PKGNM"`"
-export CATEGORY="`/usr/bin/cut -d "/" -f 1 <<< "$PKGNM"`"
+export PKG="`/usr/bin/cut -d "/" -f 2 <<< "${PKGNM}"`"
+export CATEGORY="`/usr/bin/cut -d "/" -f 1 <<< "${PKGNM}"`"
 # Package filename
-export PKG_FILENAME="`/usr/bin/sed 's/ /./g' <<< $NAME`"
-# POSIX regex that will remove 'https://' and anything after '.<tld>'.
+export PKG_FILENAME="`/usr/bin/sed 's/ /./g' <<< ${NAME}`"
+# POSIX regex that will remove 'https://' and anything after '.<tld>'
 export mirror_basename=${${MIRROR#*//}%%/*}
 ##############     END       ##############
 
@@ -49,7 +55,7 @@ export mirror_basename=${${MIRROR#*//}%%/*}
   if [ -f "/etc/make.cfg" ]; then
     . "/etc/make.cfg"
   else
-    printf "${RED}ERROR$END: make.cfg not found!\nCopy this file from the installation media (or download it from the offcial repo) and configure it."
+    printf '%b' "${RED}ERROR$END: make.cfg not found!\nCopy this file from the installation media (or download it from the offcial repo) and configure it."
     exit 1
   fi
 
@@ -58,7 +64,7 @@ export mirror_basename=${${MIRROR#*//}%%/*}
 ############ ARE YA CHECKING SON? #########
 Checkroot(){
   if [ "`whoami`" != 'root' ] && [ "`whoami`" != 'toor' ]; then
-    printf "${YELLOW}WARNING$END: It looks like you are not logged into toor nor root user...\nWould you like to install the program on the highest userland layer (${HIUSR}) instead of installing directly on the root of the system?\n${YELLOW}WARNING$END: Some packages ${BOLD}cannot$END be installed on the highest userland layer under any circunstances.\nRegarding the first (and only) question: [Y,N]? "
+    printf '%b' "${YELLOW}WARNING$END: It looks like you are not logged into toor nor root user...\nWould you like to install the program on the highest userland layer (${HIUSR}) instead of installing directly on the root of the system?\n${YELLOW}WARNING$END: Some packages ${BOLD}cannot$END be installed on the highest userland layer under any circunstances.\nRegarding the first (and only) question: [Y,N]? "
     read -r ANTWORTEN
     if /usr/bin/grep -iq '^y' <<< "$ANTWORTEN"; then
       export USRDIR="${HIUSR}"
@@ -83,11 +89,11 @@ CheckNetwork(){
   # $MIRROR is applyed only in packages officially created, unofficial packages probabily will use some custom domain.
   printf '%s' 'Checking network connection'
   txtwait
-  if `printf "GET ${mirror_basename} HTTP/1.0\n\n" | /usr/bin/netcat "${mirror_basename}" 80 > /dev/null 2>&1`; then
-    printf "[ ${GREEN}O.K.$END ]\n"
+  if [ `printf "GET ${mirror_basename} HTTP/1.0\n\n" | /usr/bin/netcat "${mirror_basename}" 80 > /dev/null 2>&1` ]; then
+    printf '%b\n' "[ ${GREEN}O.K.$END ]\n"
   else
-    printf "[ ${RED}FAILED$END ]\n"
-    printf "${RED}ERROR$END: Apparently, this box isn't connected to the World Wide Web.\a\nIf you don't have a internet connection, try to download the raw package (a ${YELLOW}$PKG_FORMT$END which contains everything necessary to install the program), save it in a diskette/CD/SDCard/USB and install it using ${YELLOW}otto dig [raw|-r]$END.\nIf you expected to have networking on this box, do some checks. Check if the network daemon is running, if the drivers are enabled on the Kernel and if the physical devices are even working/turned on.\n"
+    printf '%b\n' "[ ${RED}FAILED$END ]\n"
+    printf '%b\n' "${RED}ERROR$END: Apparently, this box isn't connected to the World Wide Web.\a\nIf you don't have a internet connection, try to download the raw package (a ${YELLOW}$PKG_FORMT$END which contains everything necessary to install the program), save it in a diskette/CD/SDCard/USB and install it using ${YELLOW}otto dig [raw|-r]$END.\nIf you expected to have networking on this box, do some checks. Check if the network daemon is running, if the drivers are enabled on the Kernel and if the physical devices are even working/turned on.\n"
     exit 11
   fi
 }
@@ -105,7 +111,7 @@ CheckDisk(){
   DSKGROSSE=$[${BENUTZT} + ${DSKVERF}]
   PKGGROSSE_FILE=`/usr/bin/du -sk "${SRCDIR}"/uncompressed-"${PKG_FILENAME}"/src.tar | /usr/bin/awk '{print $1}'`
   PKGGROSSE_CALC=`/usr/bin/bc <<< "scale=3; ${PKGGROSSE_FILE}/1000"`
-  printf "\
+  printf '%s' "\
 Estimated total disk space: ${DSKGROSSE}MB
 Estimated used space: ${DSKVERF}MB
 Estimated space available: ${BENUTZT}MB
@@ -119,35 +125,49 @@ CheckRawPackage(){
     # For uncompress
     I="${PKGNM}" # I've called it "I" because i couldn't think of a name, sorry.
     BASENAME=`basename $I`
-    PKG_FILENAME=`/usr/bin/sed 's/.psl//' <<< $I`
-    alias extractpkg="/usr/bin/7z x $I -o "${SRCDIR}"/uncompressed-"${PKG_FILENAME}""
+    PKG_FILENAME=${I%%$PKG_FORMT}
+    alias extractpkg="/usr/bin/7z x $I -o ${SRCDIR}/uncompressed-${PKG_FILENAME}"
     EXTR_MSG="Extracting ${BASENAME}"
     # Source pkginfo
-    alias sourcepkginfo=". "${SRCDIR}"/uncompressed-"${PKG_FILENAME}"/pkginfo"
+    alias sourcepkginfo=". ${SRCDIR}/uncompressed-${PKG_FILENAME}/pkginfo"
   else 
     # Run the DownloadPackage() function
     DownloadPackage
     # Source pkginfo
-    alias sourcepkginfo=". "${SRCDIR}"/uncompressed-"${PKG_FILENAME}"/pkginfo"
+    alias sourcepkginfo=". ${SRCDIR}/uncompressed-${PKG_FILENAME}/pkginfo"
     # For uncompress
-    alias extractpkg="/usr/bin/7z x "${SRCDIR}"/"${PKG_FILENAME}""${PKG_FORMT}" -o "${SRCDIR}"/uncompressed-"${PKG_FILENAME}" -bb1" # For uncompressing downloaded packages, local pkginfo needs to be sourcered first.
+    alias extractpkg="/usr/bin/7z x ${SRCDIR}/${PKG_FILENAME}${PKG_FORMT} -o ${SRCDIR}/uncompressed-${PKG_FILENAME} -bb1" # For uncompressing downloaded packages, local pkginfo needs to be sourcered first.
     EXTR_MSG="Extracting ${PKG_FILENAME}${PKG_FORMT}"
   fi
 }
 
 CheckDependencies(){
   # I hope this don't become a non-intentional fork bomb, like recursive GNU auto*hell scripts.
-  for DEP in "`printf '%s' "${DEPS}"`"; do
-    if [ /usr/bin/grep -Fxq "${DEP}" "${CONTENTS}"` ]; then # I need to add support for SRV4 (a.k.a Heirloom's pkgtools) contents file, i just don't know how to do it right now.
-      printf "${DEP} is O.K."
+  for DEP in `printf '%s' "${DEPS}"`; do
+    if [ "`/usr/bin/grep -Fxq "${DEP}" "${CONTENTS}"`" ]; then # I need to add support for SRV4 (a.k.a Heirloom's pkgtools) contents file, i just don't know how to do it right now.
+      printf '%s\n' "${DEP} is O.K."
     else
-      printf "${YELLOW}WARNING$END: ${DEP} isn't installed. Installing it now."
-      Install_Package "${DEP}"" 
+      printf '%b\n' "${YELLOW}WARNING$END: ${DEP} isn't installed. Installing it now."
+      Install_Package "${DEP}" 
     fi
   done
 }
 
 ##############  Sure i am, dad.  ############
+
+DownwloadPackage(){
+  if [ "${SYNC_TYPE}" = 'bittorrent' ]; then
+    TORRENT="${PKGNM}"
+    sourcelocalpkginfo
+    /usr/bin/pico-torrent -s -f "${PKGDIR}"/"${TORRENT}"/pkgp2p -d "${SRCDIR}"
+  elif [ "${SYNC_TYPE}" = 'http' ] || [ "${SYNC_TYPE}" = 'ftp' ]; then
+    sourcelocalpkginfo
+    chdir "${SRCDIR}" && { /usr/bin/curl -O -# "`cat ${PKGDIR}/${PKG}/pkglink`" ; chdir -;}
+  else
+    printf "${RED}ERROR$END: ${YELLOW}SYNC_TYPE$END not set @ /etc/make.cfg.\nAre you trying to install a local package? Use ${YELLOW}-r$END with ${YELLOW}-d$END"
+    exit 1
+ fi
+}
 
 Uncompress(){
   printf '%s' "${EXTR_MSG}"
@@ -178,22 +198,8 @@ AutoClean(){
   if [ "${AUTOCLEAN}" = 'YES' ]; then
     printf '%s\n' "Cleaning "${CATEGORY}"/"${PKG}" sources." ; rm -rvf "${SRCDIR}"/"uncompressed-*" && rm -vf "${SRCDIR}"/*"${PKG_FORMT}"
   else
-    printf "${YELLOW}WARNING$END: Autocleaning is disabled, trash will stay in the system until someone with the needed permissions deletes them."
+    printf '%b\n' "${YELLOW}WARNING$END: Autocleaning is disabled, trash will stay in the system until someone with the needed permissions deletes them."
   fi
-}
-
-DownwloadPackage(){
-  if [ "${SYNC_TYPE}" = 'bittorrent' ]; then
-    TORRENT="${PKGNM}"
-    . "${PKGDIR}"/"${TORRENT}"/pkginfo # Source local pkginfo
-    /usr/bin/pico-torrent -s -f "${PKGDIR}"/"${TORRENT}"/pkgp2p -d "${SRCDIR}"
-  elif [ "${SYNC_TYPE}" = 'http' ] || [ "${SYNC_TYPE}" = 'ftp' ]; then
-    . "${PKGDIR}"/"${PKGNM}"/pkginfo # Source local pkginfo
-    chdir ${SRCDIR} && { /usr/bin/curl -O -# "`cat "${PKGDIR}/${PKG}/pkglink"`" ; chdir -;}
-  else
-    printf "${RED}ERROR$END: ${YELLOW}SYNC_TYPE$END not set @ /etc/make.cfg.\nAre you trying to install a local package? Use ${YELLOW}-r$END with ${YELLOW}-d$END"
-    exit 1
- fi
 }
 
 InstallPackage(){
@@ -227,24 +233,24 @@ RemovePackage(){
 }
 
 Update(){
-  local index_package_source="`. "${PKGDIR}"/"${PKGNM}"/pkginfo`"
+  local index_package_source="`. ${PKGDIR}/${PKGNM}/pkginfo`"
   local index_package_version="`/usr/bin/tr -d '.' <<< "${VERSION}"`"
-  local installed_package_version="`/usr/bin/grep -oP "${PKGNM}"'-[0-9]+\.[0-9]+' ${CONTENTS} | /usr/bin/tr -d '.' | /usr/bin/tr -dc '0-9'`"
-  printf "Refreshing packages catalog (${mirror_basename}) "
-  {chdir "${PKGDIR}" && { /usr/bin/git clone -v http://github.com/Projeto-Pindorama/meta.git .;}}
-  printf '%s\n' "Package index updated (`/usr/bin/date '+%Y.%m.%d @ %H:%M:%S'`)."
+  local installed_package_version="`/usr/bin/grep -oP ${PKGNM}'-[0-9]+\.[0-9]+' ${CONTENTS} | /usr/bin/tr -d '.' | /usr/bin/tr -dc '0-9'`"
+  printf '%s\n' "Refreshing packages catalog \(${mirror_basename}\) "
+  { chdir "${PKGDIR}" && { /usr/bin/git clone -v http://github.com/Projeto-Pindorama/meta.git .; } }
+  printf '%s\n' "Package index updated \(`/usr/bin/date '+%Y.%m.%d @ %H:%M:%S'`\)."
   for PKGNM in "${@}"; do
     printf '%s\n' "Checking updates for ${PKGNM}."
-    if [ "${index_package_version}" > "${installed_package_version}" ]; then
-      printf '%s' "Updating ${PKGNM} (${installed_package_version} -> ${index_package_version})"
+    if [ "${index_package_version}" \> "${installed_package_version}" ]; then
+      printf '%s' "Updating ${PKGNM} \(${installed_package_version} -> ${index_package_version}\)"
       txtwait
       /usr/bin/sed -i "/${PKGNM}-${installed_package_version}/d" "${CONTENTS}"
       /usr/bin/rm -rf /var/otto/installed/pkg/OTTO"${PKG}"
       InstallPackage "${PKGNM}"
       printf '%s\n' "Updated ${PKGNM} succesfully."
-    elif [ "${index_package_version}" < "${installed_package_version}" ]; then
+    elif [ "${index_package_version}" \< "${installed_package_version}" ]; then
       echo "${YELLOW}WARNING$END: ${PKGNM}'s index files are from an older version than installed one, downgrading."
-      printf '%s' "Downgrading ${PKGNM} (${installed_package_version} -> ${index_package_version})"
+      printf '%s' "Downgrading ${PKGNM} \(${installed_package_version} -> ${index_package_version}\)"
       txtwait
       /usr/bin/sed -i "/${PKGNM}-${installed_package_version}/d" "${CONTENTS}"
       /usr/bin/rm -rf /var/otto/installed/pkg/OTTO"${PKG}"
@@ -260,12 +266,14 @@ Update(){
 MakePackage(){
   # This first implementation will be only for pure source code.
   # I need to make it more "binary-packaging-friendly".
-  local makepkg_dir="${HOME}/packaging/${1}"
+  export makepkg_dir="${HOME}/packaging/${1}"
+  export DESTDIR="${makepkg_dir}/fakeroot"
   printf '%s\n' "Creating package skeleton for ${1}."
-  mkdir -v ${makepkg_dir}
-  mkdir -v ${makepkg_dir}/install
-  mkdir -v ${makepkg_dir}/src
-  mkdir -v ${makepkg_dir}/tmpinst
+  mkdir -v "${makepkg_dir}"
+  mkdir -v "${makepkg_dir}"/install
+  mkdir -v "${makepkg_dir}"/src
+  mkdir -v "${makepkg_dir}"/tmpinst
+  mkdir -v "${DESTDIR}"
   echo "
 PKG="${1}"
 NAME="${1} X.Y.Z '<CPU> <ARCH>bit' Copacabana"
@@ -282,8 +290,11 @@ BASEDIR='/'
 DIRSTATES='1 2'
 " > ${makepkg_dir}/pkginfo
   > ${makepkg_dir}/pkgmap
+  # Where are we dropping, boys? To a Shell?
+  #printf '%s\n' "Dropping to a UNIX Shell (${SHELL})"
+  #/bin/sh -c "cd ${makepkg_dir} ; /usr/bin/env ${SHELL}"
   # Edit pkginfo
-  #editor ${makepkg_dir}/pkginfo
+  #editor "${makepkg_dir}"/pkginfo
   exit 0
 }
 
@@ -298,7 +309,7 @@ ListPackages(){
   fi
 }
 
-Info(){ 
+ProgramInfo(){ 
   printf "\
 ${BOLD}Otto, eine Paketverwaltungs-Toolchain.$END
 Ausgabe: ${ausgabe}
@@ -330,7 +341,7 @@ OPTPARAMS="NHIlfvrd:b:u:m:"
 while getopts "${OPTPARAMS}" OPT; do
   case "${OPT}" in
     "H") Help ;;
-    "I") Info ;;
+    "I") ProgramInfo ;;
     "f") find ;;
     "v") export VERBOSE=1 ;;
     "r") export RAW_PKG=1 ;;
